package io.swagger;
/**
 *  @author Swagger automated class	
 */


import org.apache.log4j.Logger;
import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.ExitCodeGenerator;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.ComponentScan;

@SpringBootApplication
@ComponentScan(basePackages = "io.swagger")
public class Swagger2SpringBoot implements CommandLineRunner {

	final static Logger logger = Logger.getLogger(Swagger2SpringBoot.class);
	
	@Override
	public void run(String... arg0) throws Exception {
		if (arg0.length > 0 && arg0[0].equals("exitcode")) {
			throw new ExitException();
		}
	}

	/**
	 * @param args A list of args
	 * @throws Exception exception generated by spring boot
	 */
	public static void main(String[] args) throws Exception {
		
		logger.debug("Start the API");
		new SpringApplication(Swagger2SpringBoot.class).run(args);
		logger.debug("API started");
	}

	class ExitException extends RuntimeException implements ExitCodeGenerator {
		private static final long serialVersionUID = 1L;

		@Override
		public int getExitCode() {
			return 10;
		}

	}
}